[[LibCURL2]]
arch = "aarch64"
git-tree-sha1 = "d6e8004a5d50c0a992cb32d967c325dd51dd03ed"
os = "macos"

    [[LibCURL2.download]]
    sha256 = "d7af43be2978f89063dd6ef68eea56be59e1cc19536092a3076ab980ada088e7"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.aarch64-apple-darwin.tar.gz"
[[LibCURL2]]
arch = "aarch64"
git-tree-sha1 = "aa602b5fc0130c51df2033dd5f37b01d263ea2f6"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "8295ef28478f75665dd44a35adaa4c23411a2e8c450888917bbb5f1e2a7dc8bb"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.aarch64-linux-gnu.tar.gz"
[[LibCURL2]]
arch = "aarch64"
git-tree-sha1 = "6e64e2daff5032893362dc0a1ef7814742c6af3c"
libc = "musl"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "9e6c4cf5dc1b71607878ac06128dd3142b6eb94d23fe10bf39c74de9d329c908"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.aarch64-linux-musl.tar.gz"
[[LibCURL2]]
arch = "aarch64"
git-tree-sha1 = "9b5acaa2f2fb45aedd61fa54d28f40a628323d02"
os = "freebsd"

    [[LibCURL2.download]]
    sha256 = "14ac24bb714b47243a55469b7406b029830bd4e539f13a87e2a31380acbf2964"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "00f6432287d43b5e8c3c47a2410c43c038292af0"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "9963c1c4256cd2a0da3439a334cfd468791be2165f7a4a570357fe8584c6f25c"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f89baffa8b4c8b3e31331d45db049460daba9d6e"
libc = "musl"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "beebdbd211ff987106f3b2140705577ec335d76682da2bbff5e969127ac33591"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa869683fa1a649ce288f1692aff9b1ad54586de"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "03c923fd93370cb1e02536951257ab50931bec98616516e9219c85764faf96a7"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7155f4bacf7187d78a1221b041cb7371cbd13d74"
libc = "musl"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "6c9465627490195f85a1e81b9817a9c4243816ced6e79f729b00a08c66925054"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL2]]
arch = "i686"
git-tree-sha1 = "3b2e1748c0225b4da106982aec9656954c4c5dca"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "638c9f38978f2c7eb064eb6f91fc5ee0b32a21c6dd39500527069489629e3844"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.i686-linux-gnu.tar.gz"
[[LibCURL2]]
arch = "i686"
git-tree-sha1 = "b2058e812475de13b31f7e5c98e4ec5675ebea47"
libc = "musl"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "f8b80499794d924b4bb2058eba3cdcbf150f506353c827dd22736fe6c1e7b0e5"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.i686-linux-musl.tar.gz"
[[LibCURL2]]
arch = "i686"
git-tree-sha1 = "3b83203f68287553dce640ac38fa18103238289c"
os = "windows"

    [[LibCURL2.download]]
    sha256 = "9ebe7d4b19b3d2a775006eb22a5fc17be9aecaaecb8403066dad177e2c2ce3fd"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.i686-w64-mingw32.tar.gz"
[[LibCURL2]]
arch = "powerpc64le"
git-tree-sha1 = "f33047f8dea16388d69afca44870363ce93a0ece"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "51e820b492a4a6dc9f85f2d78281380a71076952cdd3cce6fbae0efa36129340"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "ce795731ba47dca61b1a4512bbcad05ae55832d3"
os = "macos"

    [[LibCURL2.download]]
    sha256 = "8ba0cd499cf3f49968489b0d49c866ced02ff7082776f6f25e0220ef27441e1f"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-apple-darwin.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "bc28ccbe3e5368663440264bd1cba2c232298f2a"
libc = "glibc"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "87e45f4607f8d074b23473e1dcdeb922322f9ab2a1bfddc5303a8b5e5cd18414"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-linux-gnu.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "fe88afe0358dcc05ae66dc1fa50eb32d78763695"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL2.download]]
    sha256 = "fdbbdcb4f286fce5765a56e0a710e5ac4aaadcce33cd602ef632593790c2c0b2"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "3370d696282846325e2157f1aa2a07bf774fb10b"
libc = "musl"
os = "linux"

    [[LibCURL2.download]]
    sha256 = "e5dd54c135f64e670db20c742f5503e40cd485906e8cf76936cd6ebca22eac05"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-linux-musl.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "5db95d633f4320c3e1427641dbbd0ad3bdd2b2aa"
os = "freebsd"

    [[LibCURL2.download]]
    sha256 = "31ace6fb69a1a828297f3d3609431d3eff3c2a7d69aeb0e6c14ff5ce0a6fec2f"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL2]]
arch = "x86_64"
git-tree-sha1 = "cd4648d07f611daabe95e08d925d0773f2183c6f"
os = "windows"

    [[LibCURL2.download]]
    sha256 = "bc3724a24597d6d14a8aa9aebac1554d7bb26699e87857a628ff291c1909f1f2"
    url = "https://github.com/maxfadson/LibCURL2_jll.jl/releases/download/8.11.0-libcurl2-ldap/LibCURL2.v8.11.0.x86_64-w64-mingw32.tar.gz"
