# Autogenerated wrapper script for LibCURL2_jll for x86_64-w64-mingw32
export libcurl

using LibSSH2_jll
using Zlib_jll
using nghttp2_jll
JLLWrappers.@generate_wrapper_header("LibCURL2")
JLLWrappers.@declare_library_product(libcurl, "libcurl-4.dll")
function __init__()
    JLLWrappers.@generate_init_header(LibSSH2_jll, Zlib_jll, nghttp2_jll)
    JLLWrappers.@init_library_product(
        libcurl,
        "bin\\libcurl-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
